### Which products have the highest revenue?

In [26]:
from dotenv import load_dotenv
from databricks.connect import DatabricksSession
import os

load_dotenv() 

spark = DatabricksSession.builder \
    .host(os.getenv("DATABRICKS_HOST")) \
    .token(os.getenv("DATABRICKS_TOKEN")) \
    .serverless(True) \
    .getOrCreate()

# All audit log

In [17]:
spark.sql("""
    SELECT
    *
    FROM system.access.audit
    WHERE service_name = 'unityCatalog'
    ORDER BY event_time DESC
    LIMIT 20;
""").show()

+--------------------+------------+-------+--------------------+----------+-----------------+--------------------+--------------------+--------------------+------------+--------------------+--------------------+--------------------+--------------------+-------------+--------------------+--------------------+
|          account_id|workspace_id|version|          event_time|event_date|source_ip_address|          user_agent|          session_id|       user_identity|service_name|         action_name|          request_id|      request_params|            response|  audit_level|            event_id|   identity_metadata|
+--------------------+------------+-------+--------------------+----------+-----------------+--------------------+--------------------+--------------------+------------+--------------------+--------------------+--------------------+--------------------+-------------+--------------------+--------------------+
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:58:...|2026-04-26|    172.21.151.27|Delta-Sharing-Spa...|                NULL|{yaobx04@gmail.co...|unityCatalog|deltaSharingProxy...|a7ac69fd-e2eb-43a...|{catalog_name -> ...|   {200, NULL, NULL}|ACCOUNT_LEVEL|a6826494-8bac-3d3...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:58:...|2026-04-26|    172.21.146.32|Delta-Sharing-Spa...|                NULL|{yaobx04@gmail.co...|unityCatalog|deltaSharingProxy...|95444a64-c57d-4e0...|{catalog_name -> ...|   {200, NULL, NULL}|ACCOUNT_LEVEL|7945d96e-187d-36a...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:58:...|2026-04-26|    172.21.151.27|Apache-HttpClient...|                NULL|{yaobx04@gmail.co...|unityCatalog|metadataAndPermis...|a32cc8c0-d5b7-44c...|{include_delta_me...|{200, NULL, {"sys...|ACCOUNT_LEVEL|cfd25a4a-2b4f-367...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:58:...|2026-04-26|                 |                NULL|                NULL| {System-User, NULL}|unityCatalog|        updateTables|9058d04f-3145-4d6...|{etag -> CAESCAAA...|{200, NULL, {"ful...|ACCOUNT_LEVEL|a541caa9-6988-3a4...|{NULL, System-Use...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:58:...|2026-04-26|                 |                NULL|                NULL| {System-User, NULL}|unityCatalog|            getTable|9058d04f-3145-4d6...|{full_name_arg ->...|{200, NULL, {"ful...|ACCOUNT_LEVEL|62c6bf1c-255b-3d8...|{NULL, System-Use...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:58:...|2026-04-26|    172.21.151.27|Delta-Sharing-Spa...|                NULL|{yaobx04@gmail.co...|unityCatalog|deltaSharingProxy...|9f2811b7-74c3-416...|{catalog_name -> ...|   {200, NULL, NULL}|ACCOUNT_LEVEL|8a35aa35-c3bf-352...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:58:...|2026-04-26|    172.21.151.27|Apache-HttpClient...|                NULL|{yaobx04@gmail.co...|unityCatalog|metadataAndPermis...|536bba1b-6e7b-45d...|{include_delta_me...|{200, NULL, {"sys...|ACCOUNT_LEVEL|7288526f-9671-3a6...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:56:...|2026-04-26|    172.21.146.32|Delta-Sharing-Spa...|                NULL|{yaobx04@gmail.co...|unityCatalog|deltaSharingProxy...|7a53eca9-d90c-450...|{catalog_name -> ...|   {200, NULL, NULL}|ACCOUNT_LEVEL|395ec017-b1f2-3eb...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:56:...|2026-04-26|    172.21.146.32|Delta-Sharing-Spa...|                NULL|{yaobx04@gmail.co...|unityCatalog|deltaSharingProxy...|acd7c5e1-a25a-445...|{catalog_name -> ...|   {200, NULL, NULL}|ACCOUNT_LEVEL|be235da7-1113-3c9...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:56:...|2026-04-26|    172.21.146.32|Apache-HttpClient...|                NULL|{yaobx04@gmail.co...|unityCatalog|metadataAndPermis...|86c85c48-88ee-40b...|{include_delta_me...|{200, NULL, {"sys...|ACCOUNT_LEVEL|c114d0af-fb83-362...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:56:...|2026-04-26|                 |                NULL|                NULL| {System-User, NULL}|unityCatalog|        updateTables|7226dc40-8392-484...|{etag -> CAESCAAA...|{200, NULL, {"ful...|ACCOUNT_LEVEL|d822a62d-63a0-31e...|{NULL, System-Use...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:56:...|2026-04-26|                 |                NULL|                NULL| {System-User, NULL}|unityCatalog|            getTable|7226dc40-8392-484...|{full_name_arg ->...|{200, NULL, {"ful...|ACCOUNT_LEVEL|80da45d2-3390-354...|{NULL, System-Use...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:56:...|2026-04-26|    172.21.146.32|Delta-Sharing-Spa...|                NULL|{yaobx04@gmail.co...|unityCatalog|deltaSharingProxy...|dd4cdaec-ad42-43e...|{catalog_name -> ...|   {200, NULL, NULL}|ACCOUNT_LEVEL|3b898f58-6891-39a...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:56:...|2026-04-26|    172.21.146.32|Apache-HttpClient...|                NULL|{yaobx04@gmail.co...|unityCatalog|metadataAndPermis...|f2e2cda1-e202-469...|{include_delta_me...|{200, NULL, {"sys...|ACCOUNT_LEVEL|52f25125-0954-3d4...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:55:...|2026-04-26|  202.133.223.145|Mozilla/5.0 (Maci...|ephemeral-b68e334...|{yaobx04@gmail.co...|unityCatalog|           authzEval|da7aee75-5857-43d...|{actions -> {"{\"...|     {200, NULL, {}}|ACCOUNT_LEVEL|256af51a-dd5b-380...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:55:...|2026-04-26|  202.133.223.145|Mozilla/5.0 (Maci...|ephemeral-25838a2...|{yaobx04@gmail.co...|unityCatalog|getEffectivePermi...|dc3356c1-44a0-4b8...|{securable_type -...|     {200, NULL, {}}|ACCOUNT_LEVEL|3b325021-e8a3-329...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:55:...|2026-04-26|  202.133.223.145|Mozilla/5.0 (Maci...|ephemeral-bf60e62...|{yaobx04@gmail.co...|unityCatalog|           authzEval|90db1d66-cb6b-4da...|{actions -> {"set...|     {200, NULL, {}}|ACCOUNT_LEVEL|2f9ae9ac-4a52-32a...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:55:...|2026-04-26|  202.133.223.145|Mozilla/5.0 (Maci...|ephemeral-d929264...|{yaobx04@gmail.co...|unityCatalog|           authzEval|e74b0c19-f653-426...|{actions -> {"set...|     {200, NULL, {}}|ACCOUNT_LEVEL|64be7aa8-d672-371...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:55:...|2026-04-26|  202.133.223.145|Mozilla/5.0 (Maci...|ephemeral-5671549...|{yaobx04@gmail.co...|unityCatalog|           authzEval|2c6faf41-157f-428...|{actions -> {"{\"...|     {200, NULL, {}}|ACCOUNT_LEVEL|6b5c7ced-ba9b-3e7...|{yaobx04@gmail.co...|
|17ecef56-5243-412...|           0|    2.0|2026-04-26 10:55:...|2026-04-26|  202.133.223.145|Mozilla/5.0 (Maci...|ephemeral-afaca4e...|{yaobx04@gmail.co...|unityCatalog|           authzEval|69d1eff3-0795-4e9...|{actions -> {"{\"...|     {200, NULL, {}}|ACCOUNT_LEVEL|b9acca19-e265-378...|{yaobx04@gmail.co...|
+--------------------+------------+-------+--------------------+----------+-----------------+--------------------+--------------------+--------------------+------------+--------------------+--------------------+--------------------+--------------------+-------------+--------------------+--------------------+

# Who accessed the sensitive customers data?

In [28]:
spark.sql("""
    SELECT
        account_id,
        event_time,
        source_ip_address,
        user_identity.email,    
        action_name,
        request_params.table_full_name,
        request_params.operation
    FROM system.access.audit
    WHERE service_name = 'unityCatalog'
      AND request_params.table_full_name = 'workspace.gold.scd_customers'
""").toPandas()

,account_id,event_time,source_ip_address,email,action_name,table_full_name,operation
0,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-12 11:06:27.682,172.21.153.199,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ_WRITE
1,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-12 11:20:20.158,,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ
2,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-12 11:20:22.234,,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ
3,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-12 11:20:31.449,,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ_WRITE
4,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-12 11:20:31.189,,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ_WRITE
...,...,...,...,...,...,...,...
149,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-26 06:22:50.035,,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ
150,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-26 06:23:00.494,,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ
151,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-26 06:22:41.999,172.21.151.27,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ_WRITE
152,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-26 06:22:57.471,,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ
153,17ecef56-5243-4126-ac90-0e058e29a06d,2026-04-26 08:53:20.143,,yaobx04@gmail.com,generateTemporaryTableCredential,workspace.gold.scd_customers,READ

# Any denied access?

In [19]:
spark.sql("""
    SELECT
        event_time,
        user_identity.email,                     
        action_name,
        request_params.table_full_name,
        response.error_message
    FROM system.access.audit
    WHERE service_name = 'unityCatalog'
      AND response.status_code != 200
      AND request_params.table_full_name LIKE 'workspace.%'
    ORDER BY event_time DESC
""").toPandas()

Empty DataFrame
Columns: [event_time, attempted_by, action_name, table_attempted, reason_denied]
Index: []

# Anyone change access recently?

In [20]:
spark.sql("""
    SELECT
        event_time,
        user_identity.email,                     
        action_name,
        request_params.securable_full_name,     
        request_params.changes              
    FROM system.access.audit
    WHERE service_name = 'unityCatalog'
      AND action_name IN (
          'updatePermissions',
          'grantPermissions',
          'revokePermissions'
      )
    ORDER BY event_time DESC
""").toPandas()

Empty DataFrame
Columns: [event_time, email, action_name, securable_full_name, changes]
Index: []